trailingComma: "all"
semi: true
singleQuote: false
importOrder:
  [
    "^(react/(.*)$)|^(react$)",
    "^(next/(.*)$)|^(next$)",
    "<THIRD_PARTY_MODULES>",
    "",
    "~/(.*)$",
    "",
    "^types$",
    "^@/lib/(.*)$",
    "^@/hooks/(.*)$",
    "^@/components/ui/(.*)$",
    "^@/components/(.*)$",
    "",
    "^[./]",
    "^@/app/assets/(.*)$",
  ]
plugins: ["@ianvs/prettier-plugin-sort-imports", "prettier-plugin-tailwindcss"]
